### ISSUE TITLE
closed() function

### ISSUE THREAD

**Issue by Kinzi** [jofftiquez/vue-stripe-checkout#17]
It seems like the `closed()` function is not supported? I have a spinner that I need to hide if a user closed the stripe via the "x"...

I tried adding `closed()` to the open function in the component (preferred) and also to the options object in the set up. Neither seems to get called...

Any ideas?

(I'm using nuxt btw)

```
this.$checkout.open({
          name: 'Checkout',
          amount: this.total * 100,
          email: this.client.email,
          token: (token) => {
          },
          closed: () => {
            console.log('closed')
            this.spinner = false
          }
        })
```

**Comment by jofftiquez** [comment]
Hi @Kinzi Am gonna check this now.

**Comment by jofftiquez** [comment]
Found it. 

[This line](https://github.com/jofftiquez/vue-stripe-checkout/blob/master/src/index.js#L25) causes the problem. Apparently if I call the `.close` option inside the stripe implementation it will swallow the `.close` option in the component. 

That line of code is related to #12 . 

I will consider fixing this for you because I think the `.close` option in the component is more important than the issue in #12 .

**Comment by jofftiquez** [comment]
@Kinzi please update to `1.0.7`

**Comment by Kinzi** [comment]
@jofftiquez Great it's working! Thanks for the quick fix :)
